### PR TITLE
Added BondOrder script.

### PR DESCRIPTION
**Pull request by bdice**
Added a new script for rendering BondOrder based on the current view orientation.

image

### CODE REVIEW

**Comment by bdice** [comment]
We probably need some way to indicate which scripts are pipeline modifiers and which are viewport layers. This script is a viewport layer. Perhaps we should make subdirectories for each kind?

**Review by Tobias-Dwyer — APPROVED** [review]
I appears to work! Tried it on a small bcc system and got the correct bond order it seems. Only thing I would like is maybe a comment on choosing the 'r_max' or just to link back to freud on that because I wasn't sure what to pick for my system. I assume it would be just a radius where you interact with your nearest neighbor but not second nearest?

**Comment by bdice** [comment]
@Tobias-Dwyer Perhaps a link to https://freud.readthedocs.io/en/latest/topics/querying.html#query-arguments ?

**Comment by Tobias-Dwyer** [comment]
> @Tobias-Dwyer Perhaps a link to https://freud.readthedocs.io/en/latest/topics/querying.html#query-arguments ? And an additional comment like "Suggested value is the first trough of g(r)"?

that would be PERFECT :D

**Comment by bdice** [comment]
I used the GUI modifier function arguments that @cbkerr demonstrated. I think I found a bug in OVITO, I am curious if others have seen this on Linux/Mac.
https://www.ovito.org/forum/topic/gui-not-updating-parameters-to-viewport-python-script/#postid-2175

I'm going to go ahead and merge this PR.

**Pull request merged**
